import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { supabase } from "@/lib/supabase";
import type { Tool } from "@/lib/types";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

const MM_PER_INCH = 25.4;

interface ToolWithDesc extends Tool {
  generatedDescription: string;
}

/** Build a description from geometry fields, using the tool's original unit. */
function generateDescription(tool: Tool): string {
  const isInches = tool.unit_original?.toLowerCase() === "inches";
  const unit = isInches ? '"' : "mm";

  const parts: string[] = [];

  if (tool.geo_dc != null) {
    const val = isInches ? tool.geo_dc / MM_PER_INCH : tool.geo_dc;
    parts.push(`${formatDim(val, isInches)}${unit}`);
  }

  if (tool.type) {
    parts.push(tool.type);
  }

  if (tool.geo_nof != null) {
    parts.push(`${tool.geo_nof}FL`);
  }

  if (tool.geo_oal != null) {
    const val = isInches ? tool.geo_oal / MM_PER_INCH : tool.geo_oal;
    parts.push(`${formatDim(val, isInches)}${unit} OAL`);
  }

  return parts.join(" ").toUpperCase();
}

function formatDim(val: number, isInches: boolean): string {
  // Try to show clean fractions for common inch sizes
  if (isInches) {
    const frac = toFraction(val);
    if (frac) return frac;
    return val.toFixed(4);
  }
  return val.toFixed(2);
}

/** Convert a decimal inch value to a common fraction if it matches. */
function toFraction(val: number): string | null {
  const fractions: [number, string][] = [
    [1 / 64, "1/64"], [1 / 32, "1/32"], [3 / 64, "3/64"], [1 / 16, "1/16"],
    [5 / 64, "5/64"], [3 / 32, "3/32"], [7 / 64, "7/64"], [1 / 8, "1/8"],
    [9 / 64, "9/64"], [5 / 32, "5/32"], [11 / 64, "11/64"], [3 / 16, "3/16"],
    [13 / 64, "13/64"], [7 / 32, "7/32"], [15 / 64, "15/64"], [1 / 4, "1/4"],
    [17 / 64, "17/64"], [9 / 32, "9/32"], [19 / 64, "19/64"], [5 / 16, "5/16"],
    [21 / 64, "21/64"], [11 / 32, "11/32"], [23 / 64, "23/64"], [3 / 8, "3/8"],
    [25 / 64, "25/64"], [13 / 32, "13/32"], [27 / 64, "27/64"], [7 / 16, "7/16"],
    [29 / 64, "29/64"], [15 / 32, "15/32"], [31 / 64, "31/64"], [1 / 2, "1/2"],
    [33 / 64, "33/64"], [17 / 32, "17/32"], [35 / 64, "35/64"], [9 / 16, "9/16"],
    [37 / 64, "37/64"], [19 / 32, "19/32"], [39 / 64, "39/64"], [5 / 8, "5/8"],
    [41 / 64, "41/64"], [21 / 32, "21/32"], [43 / 64, "43/64"], [11 / 16, "11/16"],
    [45 / 64, "45/64"], [23 / 32, "23/32"], [47 / 64, "47/64"], [3 / 4, "3/4"],
    [49 / 64, "49/64"], [25 / 32, "25/32"], [51 / 64, "51/64"], [13 / 16, "13/16"],
    [53 / 64, "53/64"], [27 / 32, "27/32"], [55 / 64, "55/64"], [7 / 8, "7/8"],
    [57 / 64, "57/64"], [29 / 32, "29/32"], [59 / 64, "59/64"], [15 / 16, "15/16"],
    [61 / 64, "61/64"], [31 / 32, "31/32"], [63 / 64, "63/64"],
    [1, "1"], [1.5, "1-1/2"], [2, "2"], [2.5, "2-1/2"], [3, "3"], [4, "4"],
  ];

  for (const [num, str] of fractions) {
    if (Math.abs(val - num) < 0.0005) return str;
  }

  // Check for whole + fraction combos (e.g. 1-1/4)
  const whole = Math.floor(val);
  if (whole >= 1 && val - whole > 0.001) {
    const remainder = val - whole;
    for (const [num, str] of fractions) {
      if (Math.abs(remainder - num) < 0.0005) return `${whole}-${str}`;
    }
  }

  return null;
}

function buildFusionScript(tools: ToolWithDesc[]): string {
  // Group by library
  const byLibrary = new Map<string, ToolWithDesc[]>();
  for (const t of tools) {
    const lib = t.libraries?.library_name ?? "Unknown";
    const list = byLibrary.get(lib) ?? [];
    list.push(t);
    byLibrary.set(lib, list);
  }

  const updates = tools.map(
    (t) => `    "${t.fusion_guid}": "${t.generatedDescription.replace(/"/g, '\\"')}",`
  ).join("\n");

  return `# ─────────────────────────────────────────────────────────────
# Datum — Fill Missing Tool Descriptions
# Generated by Datum UI (${new Date().toISOString().slice(0, 10)})
# ─────────────────────────────────────────────────────────────
# Paste this into Fusion 360: Utilities → Scripts and Add-Ins → +
# Creates a new script, paste into the .py file, and Run.
#
# Libraries affected: ${[...byLibrary.keys()].join(", ")}
# Tools to update: ${tools.length}
# ─────────────────────────────────────────────────────────────

import adsk.core
import adsk.cam
import traceback

UPDATES = {
${updates}
}

def run(context):
    app = adsk.core.Application.get()
    ui = app.userInterface
    updated = 0
    errors = []

    try:
        camMgr = adsk.cam.CAMManager.get()
        libMgr = camMgr.libraryManager
        toolLibs = libMgr.toolLibraries

        # Walk all library URLs (local + cloud)
        for url in toolLibs.urls:
            lib = toolLibs.toolLibraryAtURL(url)
            for i in range(lib.count):
                tool = lib.item(i)
                guid = tool.parameters.itemByName("guid")
                if guid and guid.value.stringValue in UPDATES:
                    desc = tool.parameters.itemByName("description")
                    if desc:
                        desc.value.stringValue = UPDATES[guid.value.stringValue]
                        updated += 1

            # Save the library back
            if updated > 0:
                toolLibs.replaceToolLibrary(url, lib)

        ui.messageBox(
            f"Done! Updated {updated} of {len(UPDATES)} tool descriptions.\\n"
            f"Save your libraries and let Fusion sync to the cloud.",
            "Datum — Description Update"
        )

    except Exception:
        ui.messageBox("Error:\\n" + traceback.format_exc(), "Datum Script Error")
`;
}

export function ScriptsPage() {
  const [tools, setTools] = useState<ToolWithDesc[]>([]);
  const [loading, setLoading] = useState(true);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    async function fetch() {
      const { data, error } = await supabase
        .from("tools")
        .select("*, libraries(library_name, vendor, source_modified_at)")
        .or("description.is.null,description.eq.")
        .order("type")
        .order("geo_dc");

      if (error) {
        console.error("Failed to fetch tools:", error);
        setLoading(false);
        return;
      }

      const withDesc = (data ?? []).map((t) => ({
        ...t,
        generatedDescription: generateDescription(t),
      }));
      setTools(withDesc);
      setLoading(false);
    }
    fetch();
  }, []);

  const script = tools.length > 0 ? buildFusionScript(tools) : "";

  async function copyScript() {
    try {
      await navigator.clipboard.writeText(script);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {}
  }

  if (loading) {
    return <div className="py-12 text-center text-muted-foreground">Loading...</div>;
  }

  return (
    <div className="space-y-6">
      <div>
        <Link to="/" className="text-sm text-muted-foreground hover:underline">
          &larr; All tools
        </Link>
      </div>

      <div>
        <h1 className="text-2xl font-semibold tracking-tight">
          Fix Missing Descriptions{" "}
          <span className="text-muted-foreground font-normal">
            ({tools.length})
          </span>
        </h1>
        <p className="mt-1 text-sm text-muted-foreground">
          These tools have no description in Fusion. Datum generated one from their geometry.
          Copy the script below and run it in Fusion 360 to update them at the source.
        </p>
      </div>

      {tools.length === 0 ? (
        <Card>
          <CardContent className="py-8 text-center text-sm text-muted-foreground">
            All tools have descriptions. Nothing to fix.
          </CardContent>
        </Card>
      ) : (
        <>
          <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
            {tools.map((tool) => (
              <Card key={tool.id}>
                <CardHeader className="pb-2">
                  <CardTitle className="text-sm font-mono">
                    {tool.generatedDescription}
                  </CardTitle>
                </CardHeader>
                <CardContent className="space-y-1 text-xs text-muted-foreground">
                  <div className="flex items-center gap-2">
                    <Badge variant="secondary">{tool.type}</Badge>
                    {tool.libraries?.library_name && (
                      <span>{tool.libraries.library_name}</span>
                    )}
                  </div>
                  <div className="font-mono text-[10px] truncate">
                    GUID: {tool.fusion_guid}
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>

          <Card>
            <CardHeader>
              <div className="flex items-center justify-between">
                <CardTitle className="text-base">Fusion 360 Script</CardTitle>
                <button
                  onClick={copyScript}
                  className="rounded-md border border-border px-3 py-1.5 text-xs transition-colors hover:bg-accent"
                >
                  {copied ? "Copied!" : "Copy to clipboard"}
                </button>
              </div>
              <p className="text-xs text-muted-foreground">
                Utilities &rarr; Scripts and Add-Ins &rarr; Create a new script &rarr; paste &rarr; Run
              </p>
            </CardHeader>
            <CardContent>
              <pre className="max-h-96 overflow-auto rounded-md bg-muted p-4 text-xs font-mono whitespace-pre">
                {script}
              </pre>
            </CardContent>
          </Card>
        </>
      )}
    </div>
  );
}
